//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputSys/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Instance"",
            ""id"": ""b62b8480-ee8f-42dc-80a6-dee327dc7657"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""1e7ab502-28b7-482a-bbef-bab931689862"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StopMoving"",
                    ""type"": ""Button"",
                    ""id"": ""a75f92d8-c3b2-44e8-b1c1-d788f54ec807"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use"",
                    ""type"": ""Button"",
                    ""id"": ""8717bccd-d33c-4714-b207-30155cc46784"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IndicatorCast"",
                    ""type"": ""Value"",
                    ""id"": ""4af99fed-e084-421c-af26-522b247eb9fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AbilityQ"",
                    ""type"": ""Button"",
                    ""id"": ""42c10d7a-2798-4d54-8382-87362bec8ade"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityW"",
                    ""type"": ""Button"",
                    ""id"": ""53559240-e0d0-497c-bd82-935843233897"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityE"",
                    ""type"": ""Button"",
                    ""id"": ""987f0421-58d4-4cbe-b63c-3fde44c47a11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityR"",
                    ""type"": ""Button"",
                    ""id"": ""0b68adb4-0ac6-4bea-a317-8f9fc6812823"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Roster"",
                    ""type"": ""Value"",
                    ""id"": ""9ea72124-05a3-4da3-903a-5e6228377458"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""e7f3840d-0ed9-455a-8fc1-b7e05937c952"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraZoom"",
                    ""type"": ""Value"",
                    ""id"": ""b98920cf-5b78-429e-86be-2bb9e4519457"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5952c205-0202-43cc-875b-b9abfd7ee804"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b713cc6-50cc-442f-9d66-4417770d74cc"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""AbilityQ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bffba76-d672-4391-be87-e8e455864ca1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""AbilityW"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c92438a-96ea-42fa-bd6d-631e0ee1a4e7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""AbilityE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bbc2293-bea3-4d8f-bde4-f02d7e54f21d"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""AbilityR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2477bb5c-e1aa-4274-b84e-69de1a55d362"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ba54acc-a85d-48f8-bc22-9597d5b956fd"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""153b42b1-a93a-4148-a497-99a538e2ddd3"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Roster"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""565b6e9d-463b-4d8e-82d3-04ba0dde92ae"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1eb70dd0-cac4-40ea-bf7b-fcdeb7b4e0a3"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""IndicatorCast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed0d1f8b-da95-4362-a219-b7b272f12b44"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""StopMoving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InstanceDead"",
            ""id"": ""77e9e863-39fd-4c56-aeb1-d2a2b47f460f"",
            ""actions"": [
                {
                    ""name"": ""Roster"",
                    ""type"": ""Button"",
                    ""id"": ""493c08bf-e1b7-487e-a95f-0b29cc77da88"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""543fd08f-c2a1-413d-8d57-ea6c06dd020b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraZoom"",
                    ""type"": ""Value"",
                    ""id"": ""21ce2c5d-3d1b-433a-9299-25252a6bd699"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2983a7c9-673e-4cc6-8929-07413455949b"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5627b43-c612-408b-9412-e9905ec91008"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ed0babe-1378-48ef-ac82-252858b385bb"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Roster"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Hub"",
            ""id"": ""257ee699-f598-41ea-b528-a8fa45df0e1f"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""bf8e6337-1ee5-45aa-9ce2-c9e7eacba80f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StopMoving"",
                    ""type"": ""Button"",
                    ""id"": ""cb956eec-8341-494d-9ef0-539b63e61b7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Collection"",
                    ""type"": ""Button"",
                    ""id"": ""d8ec06cc-f385-4755-b323-00de56ed945a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""ad7a1781-ee5b-4fc8-83cc-5fb869630381"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraZoom"",
                    ""type"": ""Value"",
                    ""id"": ""ac9bd440-631a-4f27-92e3-60840886c598"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8d86799b-ccae-47ec-9a0b-074b71421369"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0410f2a8-f063-4a66-8dbc-bd0f6f3a6760"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Collection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""793af12a-7673-499d-9f43-21d18d814801"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3afda0c2-f2ce-4a32-970b-4d0d7d6194d0"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""410e9d74-f9fc-4a9f-a114-89e23d772597"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""StopMoving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Collection"",
            ""id"": ""e32e5123-4ce0-4a55-b92d-dec4697a5e6c"",
            ""actions"": [
                {
                    ""name"": ""QuickEquip"",
                    ""type"": ""Button"",
                    ""id"": ""d9fea493-0baf-4b7d-9976-c8bef96f4309"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Collection"",
                    ""type"": ""Button"",
                    ""id"": ""f599d04a-19d3-410a-af30-a2c9c11c0848"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""0551cb57-d606-476e-9a73-4cae2d112620"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""1eca24fa-1008-4aed-9d3e-1b5eaed4ddd2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ecf6f840-4af9-4405-b096-76a963d21606"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""QuickEquip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8aef6448-5d8f-4edc-b1d8-3b615381a601"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Collection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98fe143a-a63a-4225-af3f-bec72c252401"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""583e8dd6-13fb-40df-931a-21c6d8c71191"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ThomasTesting"",
            ""id"": ""8e8c2cc2-b7e0-47c6-85f3-982755c7d10d"",
            ""actions"": [
                {
                    ""name"": ""FireButton"",
                    ""type"": ""Button"",
                    ""id"": ""9aeaf935-8edd-415e-bf24-d94722b82f4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireOff"",
                    ""type"": ""Button"",
                    ""id"": ""772c9034-4e09-4c13-9100-d3e1ae7972b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ced32142-a7b7-4a5e-bb38-472c472b892e"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b70e695-287a-414f-b264-a52974e1dc5c"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireOff"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Instance
        m_Instance = asset.FindActionMap("Instance", throwIfNotFound: true);
        m_Instance_Move = m_Instance.FindAction("Move", throwIfNotFound: true);
        m_Instance_StopMoving = m_Instance.FindAction("StopMoving", throwIfNotFound: true);
        m_Instance_Use = m_Instance.FindAction("Use", throwIfNotFound: true);
        m_Instance_IndicatorCast = m_Instance.FindAction("IndicatorCast", throwIfNotFound: true);
        m_Instance_AbilityQ = m_Instance.FindAction("AbilityQ", throwIfNotFound: true);
        m_Instance_AbilityW = m_Instance.FindAction("AbilityW", throwIfNotFound: true);
        m_Instance_AbilityE = m_Instance.FindAction("AbilityE", throwIfNotFound: true);
        m_Instance_AbilityR = m_Instance.FindAction("AbilityR", throwIfNotFound: true);
        m_Instance_Roster = m_Instance.FindAction("Roster", throwIfNotFound: true);
        m_Instance_Menu = m_Instance.FindAction("Menu", throwIfNotFound: true);
        m_Instance_CameraZoom = m_Instance.FindAction("CameraZoom", throwIfNotFound: true);
        // InstanceDead
        m_InstanceDead = asset.FindActionMap("InstanceDead", throwIfNotFound: true);
        m_InstanceDead_Roster = m_InstanceDead.FindAction("Roster", throwIfNotFound: true);
        m_InstanceDead_Menu = m_InstanceDead.FindAction("Menu", throwIfNotFound: true);
        m_InstanceDead_CameraZoom = m_InstanceDead.FindAction("CameraZoom", throwIfNotFound: true);
        // Hub
        m_Hub = asset.FindActionMap("Hub", throwIfNotFound: true);
        m_Hub_Move = m_Hub.FindAction("Move", throwIfNotFound: true);
        m_Hub_StopMoving = m_Hub.FindAction("StopMoving", throwIfNotFound: true);
        m_Hub_Collection = m_Hub.FindAction("Collection", throwIfNotFound: true);
        m_Hub_Menu = m_Hub.FindAction("Menu", throwIfNotFound: true);
        m_Hub_CameraZoom = m_Hub.FindAction("CameraZoom", throwIfNotFound: true);
        // Collection
        m_Collection = asset.FindActionMap("Collection", throwIfNotFound: true);
        m_Collection_QuickEquip = m_Collection.FindAction("QuickEquip", throwIfNotFound: true);
        m_Collection_Collection = m_Collection.FindAction("Collection", throwIfNotFound: true);
        m_Collection_Exit = m_Collection.FindAction("Exit", throwIfNotFound: true);
        m_Collection_Scroll = m_Collection.FindAction("Scroll", throwIfNotFound: true);
        // ThomasTesting
        m_ThomasTesting = asset.FindActionMap("ThomasTesting", throwIfNotFound: true);
        m_ThomasTesting_FireButton = m_ThomasTesting.FindAction("FireButton", throwIfNotFound: true);
        m_ThomasTesting_FireOff = m_ThomasTesting.FindAction("FireOff", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Instance
    private readonly InputActionMap m_Instance;
    private IInstanceActions m_InstanceActionsCallbackInterface;
    private readonly InputAction m_Instance_Move;
    private readonly InputAction m_Instance_StopMoving;
    private readonly InputAction m_Instance_Use;
    private readonly InputAction m_Instance_IndicatorCast;
    private readonly InputAction m_Instance_AbilityQ;
    private readonly InputAction m_Instance_AbilityW;
    private readonly InputAction m_Instance_AbilityE;
    private readonly InputAction m_Instance_AbilityR;
    private readonly InputAction m_Instance_Roster;
    private readonly InputAction m_Instance_Menu;
    private readonly InputAction m_Instance_CameraZoom;
    public struct InstanceActions
    {
        private @PlayerInputActions m_Wrapper;
        public InstanceActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Instance_Move;
        public InputAction @StopMoving => m_Wrapper.m_Instance_StopMoving;
        public InputAction @Use => m_Wrapper.m_Instance_Use;
        public InputAction @IndicatorCast => m_Wrapper.m_Instance_IndicatorCast;
        public InputAction @AbilityQ => m_Wrapper.m_Instance_AbilityQ;
        public InputAction @AbilityW => m_Wrapper.m_Instance_AbilityW;
        public InputAction @AbilityE => m_Wrapper.m_Instance_AbilityE;
        public InputAction @AbilityR => m_Wrapper.m_Instance_AbilityR;
        public InputAction @Roster => m_Wrapper.m_Instance_Roster;
        public InputAction @Menu => m_Wrapper.m_Instance_Menu;
        public InputAction @CameraZoom => m_Wrapper.m_Instance_CameraZoom;
        public InputActionMap Get() { return m_Wrapper.m_Instance; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InstanceActions set) { return set.Get(); }
        public void SetCallbacks(IInstanceActions instance)
        {
            if (m_Wrapper.m_InstanceActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_InstanceActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_InstanceActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_InstanceActionsCallbackInterface.OnMove;
                @StopMoving.started -= m_Wrapper.m_InstanceActionsCallbackInterface.OnStopMoving;
                @StopMoving.performed -= m_Wrapper.m_InstanceActionsCallbackInterface.OnStopMoving;
                @StopMoving.canceled -= m_Wrapper.m_InstanceActionsCallbackInterface.OnStopMoving;
                @Use.started -= m_Wrapper.m_InstanceActionsCallbackInterface.OnUse;
                @Use.performed -= m_Wrapper.m_InstanceActionsCallbackInterface.OnUse;
                @Use.canceled -= m_Wrapper.m_InstanceActionsCallbackInterface.OnUse;
                @IndicatorCast.started -= m_Wrapper.m_InstanceActionsCallbackInterface.OnIndicatorCast;
                @IndicatorCast.performed -= m_Wrapper.m_InstanceActionsCallbackInterface.OnIndicatorCast;
                @IndicatorCast.canceled -= m_Wrapper.m_InstanceActionsCallbackInterface.OnIndicatorCast;
                @AbilityQ.started -= m_Wrapper.m_InstanceActionsCallbackInterface.OnAbilityQ;
                @AbilityQ.performed -= m_Wrapper.m_InstanceActionsCallbackInterface.OnAbilityQ;
                @AbilityQ.canceled -= m_Wrapper.m_InstanceActionsCallbackInterface.OnAbilityQ;
                @AbilityW.started -= m_Wrapper.m_InstanceActionsCallbackInterface.OnAbilityW;
                @AbilityW.performed -= m_Wrapper.m_InstanceActionsCallbackInterface.OnAbilityW;
                @AbilityW.canceled -= m_Wrapper.m_InstanceActionsCallbackInterface.OnAbilityW;
                @AbilityE.started -= m_Wrapper.m_InstanceActionsCallbackInterface.OnAbilityE;
                @AbilityE.performed -= m_Wrapper.m_InstanceActionsCallbackInterface.OnAbilityE;
                @AbilityE.canceled -= m_Wrapper.m_InstanceActionsCallbackInterface.OnAbilityE;
                @AbilityR.started -= m_Wrapper.m_InstanceActionsCallbackInterface.OnAbilityR;
                @AbilityR.performed -= m_Wrapper.m_InstanceActionsCallbackInterface.OnAbilityR;
                @AbilityR.canceled -= m_Wrapper.m_InstanceActionsCallbackInterface.OnAbilityR;
                @Roster.started -= m_Wrapper.m_InstanceActionsCallbackInterface.OnRoster;
                @Roster.performed -= m_Wrapper.m_InstanceActionsCallbackInterface.OnRoster;
                @Roster.canceled -= m_Wrapper.m_InstanceActionsCallbackInterface.OnRoster;
                @Menu.started -= m_Wrapper.m_InstanceActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_InstanceActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_InstanceActionsCallbackInterface.OnMenu;
                @CameraZoom.started -= m_Wrapper.m_InstanceActionsCallbackInterface.OnCameraZoom;
                @CameraZoom.performed -= m_Wrapper.m_InstanceActionsCallbackInterface.OnCameraZoom;
                @CameraZoom.canceled -= m_Wrapper.m_InstanceActionsCallbackInterface.OnCameraZoom;
            }
            m_Wrapper.m_InstanceActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @StopMoving.started += instance.OnStopMoving;
                @StopMoving.performed += instance.OnStopMoving;
                @StopMoving.canceled += instance.OnStopMoving;
                @Use.started += instance.OnUse;
                @Use.performed += instance.OnUse;
                @Use.canceled += instance.OnUse;
                @IndicatorCast.started += instance.OnIndicatorCast;
                @IndicatorCast.performed += instance.OnIndicatorCast;
                @IndicatorCast.canceled += instance.OnIndicatorCast;
                @AbilityQ.started += instance.OnAbilityQ;
                @AbilityQ.performed += instance.OnAbilityQ;
                @AbilityQ.canceled += instance.OnAbilityQ;
                @AbilityW.started += instance.OnAbilityW;
                @AbilityW.performed += instance.OnAbilityW;
                @AbilityW.canceled += instance.OnAbilityW;
                @AbilityE.started += instance.OnAbilityE;
                @AbilityE.performed += instance.OnAbilityE;
                @AbilityE.canceled += instance.OnAbilityE;
                @AbilityR.started += instance.OnAbilityR;
                @AbilityR.performed += instance.OnAbilityR;
                @AbilityR.canceled += instance.OnAbilityR;
                @Roster.started += instance.OnRoster;
                @Roster.performed += instance.OnRoster;
                @Roster.canceled += instance.OnRoster;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @CameraZoom.started += instance.OnCameraZoom;
                @CameraZoom.performed += instance.OnCameraZoom;
                @CameraZoom.canceled += instance.OnCameraZoom;
            }
        }
    }
    public InstanceActions @Instance => new InstanceActions(this);

    // InstanceDead
    private readonly InputActionMap m_InstanceDead;
    private IInstanceDeadActions m_InstanceDeadActionsCallbackInterface;
    private readonly InputAction m_InstanceDead_Roster;
    private readonly InputAction m_InstanceDead_Menu;
    private readonly InputAction m_InstanceDead_CameraZoom;
    public struct InstanceDeadActions
    {
        private @PlayerInputActions m_Wrapper;
        public InstanceDeadActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Roster => m_Wrapper.m_InstanceDead_Roster;
        public InputAction @Menu => m_Wrapper.m_InstanceDead_Menu;
        public InputAction @CameraZoom => m_Wrapper.m_InstanceDead_CameraZoom;
        public InputActionMap Get() { return m_Wrapper.m_InstanceDead; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InstanceDeadActions set) { return set.Get(); }
        public void SetCallbacks(IInstanceDeadActions instance)
        {
            if (m_Wrapper.m_InstanceDeadActionsCallbackInterface != null)
            {
                @Roster.started -= m_Wrapper.m_InstanceDeadActionsCallbackInterface.OnRoster;
                @Roster.performed -= m_Wrapper.m_InstanceDeadActionsCallbackInterface.OnRoster;
                @Roster.canceled -= m_Wrapper.m_InstanceDeadActionsCallbackInterface.OnRoster;
                @Menu.started -= m_Wrapper.m_InstanceDeadActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_InstanceDeadActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_InstanceDeadActionsCallbackInterface.OnMenu;
                @CameraZoom.started -= m_Wrapper.m_InstanceDeadActionsCallbackInterface.OnCameraZoom;
                @CameraZoom.performed -= m_Wrapper.m_InstanceDeadActionsCallbackInterface.OnCameraZoom;
                @CameraZoom.canceled -= m_Wrapper.m_InstanceDeadActionsCallbackInterface.OnCameraZoom;
            }
            m_Wrapper.m_InstanceDeadActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Roster.started += instance.OnRoster;
                @Roster.performed += instance.OnRoster;
                @Roster.canceled += instance.OnRoster;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @CameraZoom.started += instance.OnCameraZoom;
                @CameraZoom.performed += instance.OnCameraZoom;
                @CameraZoom.canceled += instance.OnCameraZoom;
            }
        }
    }
    public InstanceDeadActions @InstanceDead => new InstanceDeadActions(this);

    // Hub
    private readonly InputActionMap m_Hub;
    private IHubActions m_HubActionsCallbackInterface;
    private readonly InputAction m_Hub_Move;
    private readonly InputAction m_Hub_StopMoving;
    private readonly InputAction m_Hub_Collection;
    private readonly InputAction m_Hub_Menu;
    private readonly InputAction m_Hub_CameraZoom;
    public struct HubActions
    {
        private @PlayerInputActions m_Wrapper;
        public HubActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Hub_Move;
        public InputAction @StopMoving => m_Wrapper.m_Hub_StopMoving;
        public InputAction @Collection => m_Wrapper.m_Hub_Collection;
        public InputAction @Menu => m_Wrapper.m_Hub_Menu;
        public InputAction @CameraZoom => m_Wrapper.m_Hub_CameraZoom;
        public InputActionMap Get() { return m_Wrapper.m_Hub; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HubActions set) { return set.Get(); }
        public void SetCallbacks(IHubActions instance)
        {
            if (m_Wrapper.m_HubActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_HubActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_HubActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_HubActionsCallbackInterface.OnMove;
                @StopMoving.started -= m_Wrapper.m_HubActionsCallbackInterface.OnStopMoving;
                @StopMoving.performed -= m_Wrapper.m_HubActionsCallbackInterface.OnStopMoving;
                @StopMoving.canceled -= m_Wrapper.m_HubActionsCallbackInterface.OnStopMoving;
                @Collection.started -= m_Wrapper.m_HubActionsCallbackInterface.OnCollection;
                @Collection.performed -= m_Wrapper.m_HubActionsCallbackInterface.OnCollection;
                @Collection.canceled -= m_Wrapper.m_HubActionsCallbackInterface.OnCollection;
                @Menu.started -= m_Wrapper.m_HubActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_HubActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_HubActionsCallbackInterface.OnMenu;
                @CameraZoom.started -= m_Wrapper.m_HubActionsCallbackInterface.OnCameraZoom;
                @CameraZoom.performed -= m_Wrapper.m_HubActionsCallbackInterface.OnCameraZoom;
                @CameraZoom.canceled -= m_Wrapper.m_HubActionsCallbackInterface.OnCameraZoom;
            }
            m_Wrapper.m_HubActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @StopMoving.started += instance.OnStopMoving;
                @StopMoving.performed += instance.OnStopMoving;
                @StopMoving.canceled += instance.OnStopMoving;
                @Collection.started += instance.OnCollection;
                @Collection.performed += instance.OnCollection;
                @Collection.canceled += instance.OnCollection;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @CameraZoom.started += instance.OnCameraZoom;
                @CameraZoom.performed += instance.OnCameraZoom;
                @CameraZoom.canceled += instance.OnCameraZoom;
            }
        }
    }
    public HubActions @Hub => new HubActions(this);

    // Collection
    private readonly InputActionMap m_Collection;
    private ICollectionActions m_CollectionActionsCallbackInterface;
    private readonly InputAction m_Collection_QuickEquip;
    private readonly InputAction m_Collection_Collection;
    private readonly InputAction m_Collection_Exit;
    private readonly InputAction m_Collection_Scroll;
    public struct CollectionActions
    {
        private @PlayerInputActions m_Wrapper;
        public CollectionActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @QuickEquip => m_Wrapper.m_Collection_QuickEquip;
        public InputAction @Collection => m_Wrapper.m_Collection_Collection;
        public InputAction @Exit => m_Wrapper.m_Collection_Exit;
        public InputAction @Scroll => m_Wrapper.m_Collection_Scroll;
        public InputActionMap Get() { return m_Wrapper.m_Collection; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CollectionActions set) { return set.Get(); }
        public void SetCallbacks(ICollectionActions instance)
        {
            if (m_Wrapper.m_CollectionActionsCallbackInterface != null)
            {
                @QuickEquip.started -= m_Wrapper.m_CollectionActionsCallbackInterface.OnQuickEquip;
                @QuickEquip.performed -= m_Wrapper.m_CollectionActionsCallbackInterface.OnQuickEquip;
                @QuickEquip.canceled -= m_Wrapper.m_CollectionActionsCallbackInterface.OnQuickEquip;
                @Collection.started -= m_Wrapper.m_CollectionActionsCallbackInterface.OnCollection;
                @Collection.performed -= m_Wrapper.m_CollectionActionsCallbackInterface.OnCollection;
                @Collection.canceled -= m_Wrapper.m_CollectionActionsCallbackInterface.OnCollection;
                @Exit.started -= m_Wrapper.m_CollectionActionsCallbackInterface.OnExit;
                @Exit.performed -= m_Wrapper.m_CollectionActionsCallbackInterface.OnExit;
                @Exit.canceled -= m_Wrapper.m_CollectionActionsCallbackInterface.OnExit;
                @Scroll.started -= m_Wrapper.m_CollectionActionsCallbackInterface.OnScroll;
                @Scroll.performed -= m_Wrapper.m_CollectionActionsCallbackInterface.OnScroll;
                @Scroll.canceled -= m_Wrapper.m_CollectionActionsCallbackInterface.OnScroll;
            }
            m_Wrapper.m_CollectionActionsCallbackInterface = instance;
            if (instance != null)
            {
                @QuickEquip.started += instance.OnQuickEquip;
                @QuickEquip.performed += instance.OnQuickEquip;
                @QuickEquip.canceled += instance.OnQuickEquip;
                @Collection.started += instance.OnCollection;
                @Collection.performed += instance.OnCollection;
                @Collection.canceled += instance.OnCollection;
                @Exit.started += instance.OnExit;
                @Exit.performed += instance.OnExit;
                @Exit.canceled += instance.OnExit;
                @Scroll.started += instance.OnScroll;
                @Scroll.performed += instance.OnScroll;
                @Scroll.canceled += instance.OnScroll;
            }
        }
    }
    public CollectionActions @Collection => new CollectionActions(this);

    // ThomasTesting
    private readonly InputActionMap m_ThomasTesting;
    private IThomasTestingActions m_ThomasTestingActionsCallbackInterface;
    private readonly InputAction m_ThomasTesting_FireButton;
    private readonly InputAction m_ThomasTesting_FireOff;
    public struct ThomasTestingActions
    {
        private @PlayerInputActions m_Wrapper;
        public ThomasTestingActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @FireButton => m_Wrapper.m_ThomasTesting_FireButton;
        public InputAction @FireOff => m_Wrapper.m_ThomasTesting_FireOff;
        public InputActionMap Get() { return m_Wrapper.m_ThomasTesting; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ThomasTestingActions set) { return set.Get(); }
        public void SetCallbacks(IThomasTestingActions instance)
        {
            if (m_Wrapper.m_ThomasTestingActionsCallbackInterface != null)
            {
                @FireButton.started -= m_Wrapper.m_ThomasTestingActionsCallbackInterface.OnFireButton;
                @FireButton.performed -= m_Wrapper.m_ThomasTestingActionsCallbackInterface.OnFireButton;
                @FireButton.canceled -= m_Wrapper.m_ThomasTestingActionsCallbackInterface.OnFireButton;
                @FireOff.started -= m_Wrapper.m_ThomasTestingActionsCallbackInterface.OnFireOff;
                @FireOff.performed -= m_Wrapper.m_ThomasTestingActionsCallbackInterface.OnFireOff;
                @FireOff.canceled -= m_Wrapper.m_ThomasTestingActionsCallbackInterface.OnFireOff;
            }
            m_Wrapper.m_ThomasTestingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @FireButton.started += instance.OnFireButton;
                @FireButton.performed += instance.OnFireButton;
                @FireButton.canceled += instance.OnFireButton;
                @FireOff.started += instance.OnFireOff;
                @FireOff.performed += instance.OnFireOff;
                @FireOff.canceled += instance.OnFireOff;
            }
        }
    }
    public ThomasTestingActions @ThomasTesting => new ThomasTestingActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface IInstanceActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnStopMoving(InputAction.CallbackContext context);
        void OnUse(InputAction.CallbackContext context);
        void OnIndicatorCast(InputAction.CallbackContext context);
        void OnAbilityQ(InputAction.CallbackContext context);
        void OnAbilityW(InputAction.CallbackContext context);
        void OnAbilityE(InputAction.CallbackContext context);
        void OnAbilityR(InputAction.CallbackContext context);
        void OnRoster(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnCameraZoom(InputAction.CallbackContext context);
    }
    public interface IInstanceDeadActions
    {
        void OnRoster(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnCameraZoom(InputAction.CallbackContext context);
    }
    public interface IHubActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnStopMoving(InputAction.CallbackContext context);
        void OnCollection(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnCameraZoom(InputAction.CallbackContext context);
    }
    public interface ICollectionActions
    {
        void OnQuickEquip(InputAction.CallbackContext context);
        void OnCollection(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
    }
    public interface IThomasTestingActions
    {
        void OnFireButton(InputAction.CallbackContext context);
        void OnFireOff(InputAction.CallbackContext context);
    }
}
